
if GetLocale() ~= "deDE" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "1. Hintergrund"
L["2. Border"] = "2. Rahmen"
L["3. Artwork"] = "3. Artwork"
L["4. Overlay"] = "4. Overlay"
L["5. Highlight"] = "5. Hervorhebung" -- Needs review
L["Add Blend (additive)"] = "Blend-Effekt hinzufügen (additiv)"
L["Addon Buttons"] = "AddOn-Knöpfe"
L["A global profile already exists. You will be switched over to it and your UI will be reloaded, are you sure?"] = "Es existiert bereits ein globales Profil. Du wirst auf dieses gewechselt und das Interface wird neu geladen, bist du dir sicher?" -- Needs review
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "Erlaube SexyMap, das Bewegen/Ziehen von Knöpfen an der Minimap zu übernehmen. Deaktiviere diese Option, wenn du einen anderen Mod/AddOn benutzt, um die Minimap-Knöpfe zu positionieren."
L["Alpha Key (1-bit alpha)"] = "Alpha-Wert (1-bit alpha)"
L["Always"] = "Immer"
L["Are you sure you want to switch back to using a character specific profile? This will reload your UI."] = "Bist du dir sicher, dass du zurück auf das pharakterspezifische Profil wechseln willst? Dies wird dein Interface neu laden." -- Needs review
L["Armored Man"] = "Haltbarkeits-Figur"
L["A static amount to rotate the texture by."] = "Ein statischer Wert, um den den Textur gedreht werden soll."
L["Auto Zoom-Out Delay"] = "Auto-Herauszoom-Verzögerung"
L["Backdrop Color"] = "Hintergrundfarbe" -- Needs review
L["Background Color"] = "Hintergrundfarbe"
L["Background/edge"] = "Hintergrund/Kante" -- Needs review
L["Background Texture"] = "Hintergrundtextur"
L["Blend Mode"] = "Überblendmodus" -- Needs review
L["Blend (normal)"] = "Überblendung (normal)" -- Needs review
L["Border Color"] = "Rahmenfarbe" -- Needs review
L["Border Edge Size"] = "Randkantenfarbe"
L["Borders"] = "Rahmen"
L["Border Texture"] = "Rahmentextur"
L["Boss Frames"] = "Bossrahmen" -- Needs review
L["Buttons"] = "Knöpfe"
L["Calendar"] = "Kalender"
L["Capture Bars"] = "Aufnahmeleisten" -- Needs review
L["Challenge Mode Button (When Available)"] = "Herausforderungsknöpfe" -- Needs review
L["Circle"] = "Kreis"
L["Clamp to screen"] = "Am Bildschirm befestigen"
L["Clear & start over"] = "Leeren & neu anfangen"
L["Clear the current borders and start fresh"] = "Die aktuellen Rahmen löschen und neu anfangen"
L["Clock"] = "Uhr"
L["Coordinates"] = "Koordinaten"
L["Copy a Profile"] = "Kopiere ein Profil" -- Needs review
L["Copying this profile will reload your UI, are you sure?"] = "Das Kopieren Dieses Profils wird dein Interface neu laden, bist du dir sicher?" -- Needs review
L["Create a new border"] = "Neuen Rahmen erstellen"
L["Current Borders"] = "Aktuelle Rahmen"
L["Default Presets"] = "Standard-Voreinstellungen" -- Needs review
L["Delete"] = "Löschen"
L["Diamond"] = "Diamant"
L["Disable (opaque)"] = "Deaktivieren (lichtdicht/opaque)"
L["Disable Rotation"] = "Rotation deaktivieren"
L["Disabling the movers will make them reset next time you relog, are you sure?"] = "Wenn du die beweglichen Knöpfe deaktivierst, werden diese beim nächsten einloggen zurückgesetzt, bist du dir sicher?" -- Needs review
L["Drag Radius"] = "Bewegungs-Radius"
L["Dungeon Difficulty Indicator (When Available)"] = "Instanzschwierigkeitsanzeige (falls verfügbar)" -- Needs review
L["Dynamic Buttons"] = "Dynamische Knöpfe"
L["Enable"] = "Aktivieren"
L["Enable a backdrop and border for the minimap. This will let you set square borders more easily."] = "Aktiviere einen Hintergrund und Rahmen für die Minimap. Dies erleichtert die Konfiguration von eckigen Rahmen."
L["Enable a HUD minimap. This is very useful for gathering resources, but for technical reasons, the HUD map and the normal minimap can't be shown at the same time. Showing the HUD map will turn off the normal minimap."] = "Aktiviere eine HUD Minimap. Diese Anzeige ist sehr nützlich für Sammelberufe, jedoch kann das HUD und die normale Minimap nicht gleichzeitig angezeigt werden. Die normale Minimap ist während der HUD-Anzeige deaktiviert."
L["Enable Coordinates"] = "Koordinaten aktivieren"
L["Enable Hudmap"] = "Hudmap aktivieren"
L["Enable Minimap Fader"] = "Minimap-Abblendung aktivieren"
L["Enable Movers"] = "Aktiviere bewegliche Anzeigen" -- Needs review
L["Enter a name to create a new border. The name can be anything you like to help you identify that border."] = "Füge einen Namen ein, um einen neuen Rahmen zu erstellen. Der Name soll dir helfen, den Rahmen zu identifizieren."
L["Enter the full path to a texture to use. It's recommended that you use something like |cffff6600TexBrowser|r to find textures to use."] = "Füge den vollständigen Pfad der gewünschten Textur ein. Es wird empfohlen, dass du ein AddOn wie z.B. |cffff6600TexBrowser| benutzt, um nützliche Texturen zu suchen."
L["Entry Options"] = "Eintrags-Optionen" -- Needs review
L["Faded Circle (Large)"] = "Verblasster Kreis (groß)"
L["Faded Circle (Small)"] = "Verblasster Kreis (klein)"
L["Faded Square"] = "Verblasster Kreis"
L["Fader"] = "Blendregler" -- Needs review
L["Font"] = "Schrifttyp"
L["Font Color"] = "Schriftfarbe"
L["Font Size"] = "Schriftgröße"
L["Force a square texture. Fixed distortion on square textures."] = "Erzwinge eine rechteckige Textur. Feste Verformung von rechteckigen Texturen."
L["Guild Dungeon Difficulty Indicator (When Available)"] = "Gildeninstanzschwierigkeitsindikator (falls verfügbar)" -- Needs review
L["Heart"] = "Herz"
L["Height"] = "Höhe" -- Needs review
L["Hexagon"] = "Sechseck"
L["Hide default border"] = "Verstecke den Standard-Rahmen"
L["Hide the default border on the minimap."] = "Verstecke den Standard-Rahmen der Minimap"
L["Horizontal Nudge"] = "Horizontaler Anstoß" -- Needs review
L["Horizontal Position"] = "Horizontale Position"
L["HUD Color"] = "HUD-Farbe"
L["If you zoom into the map, this feature will automatically zoom out after the selected period of time (seconds). Using a value of 0 will disable Auto Zoom-Out."] = "Wenn du in die Karte hineinzoomst, wird diese Funktion nach der eingestellten Zeit (in Sekunden) automatisch wieder herauszoomen. Wird der Wert 0 verwendet, wird das automatische Herauszoomen deaktiviert." -- Needs review
L["Keybinding"] = "Tastenbelegung"
L["Layer"] = "Ebene" -- Needs review
L["Let SexyMap control button visibility"] = "Ermögliche SexyMap die Kontrolle über die Sichtbarkeit der Minimap-Knöpfe"
L["Let SexyMap handle button dragging"] = "Ermögliche SexyMap die Kontrolle über die Positionierung der Minimap-Knöpfe" -- Needs review
L["Lock Button Dragging"] = "Ziehen der Knöpfe verhindern" -- Needs review
L["Lock Coordinates"] = "Koordinaten sperren" -- Needs review
L["Lock Minimap"] = "Minimap sperren" -- Needs review
L["Lock Movers"] = "Bewegliche Knöpfe sperren" -- Needs review
L["Map Button"] = "Karten-Knopf"
L["Minimap shape"] = "Form der Minimap"
L["Mod Blend (modulative)"] = "Mod Blend (modulativ)" -- Needs review
L["Movers"] = "Bewegliche Knöpfe" -- Needs review
L["Movers Warning"] = "WARNUNG: Diese Funktion wird nicht offiziell unterstützt. Es kann zu Problemen, wie z.B. Flecken, Verlust der Quest-Verfolgung oder 'springenden' Boss-Anzeigen, führen. Blizzard Frames wie der QuestTracker und die Boss-Anzeige sind nicht für Umpositionierungen ausgelegt. Es wird empfohlen, diese durch AddOns zu ersetzen; z.B. durch UnitFrames mit Boss-Anzeige." -- Needs review
L["Name"] = "Name"
L["Never"] = "Niemals"
L["New Mail Indicator (When Available)"] = "Post-Anzeige (wenn verfügbar)"
L["No global profile exists. Your current profile will be copied over and used as the global profile, are you sure? This will also reload your UI."] = "Es existiert kein globales Profil. Das aktuelle Profil wird kopiert und als das globale Profil verwendet, bist du dir sicher? Dies wird auch das Interface neu laden." -- Needs review
L["Normal Opacity"] = "Normale Transparenz" -- Needs review
L["Objectives Tracker"] = "Aufgabenliste" -- Needs review
L["Octagon"] = "Achteck"
L["On Hover"] = "bei Überfahren (mit der Maus)" -- Needs review
L["Opacity"] = "Deckkraft/Undurchsichtigkeit"
L["Open TexBrowser"] = "Öffne TexBrowser"
L["Ping"] = "Ping"
L["Preset"] = "Voreinstellung"
L["Prevent the minimap from being moved off the screen"] = "Verhindere, dass die Minimap außerhalb des Bildschirms bewegt werden kann"
L["Profiles"] = "Profile"
L["Queue Status (PvP/LFG) Button (When Available)"] = "Warteschlangenstatus (PvP/LFG) Knopf (falls verfügbar)" -- Needs review
L["Quickly change the look of your minimap by using a minimap preset."] = "Das Aussehen der Minimap schnell ändern, indem eine Voreinstellung geladen wird" -- Needs review
L["Really delete this border?"] = "Diesen Rahmen wirklich entfernen?"
L["Really delete this preset? This can't be undone."] = "Diese Voreinstellung wirklich entfernen? Das Entfernen lässt sich nicht rückgängig machen!"
L["Really delete this profile?"] = "Dieses Profil wirklich löschen?" -- Needs review
L["(Requires button visibility control in the Buttons menu)"] = "Benötigt Knopf-Sichtbarkeits-Kontrolle im Knöpfe-Menü" -- Needs review
L["Reset Current Profile"] = "Aktuelles Profil zurücksetzen" -- Needs review
L["Reset Position"] = "Position zurücksetzen"
L["Resetting this profile will reload your UI, are you sure?"] = "Das Zurücksetzen dieses Profils wird dein UI neu laden, bist du dir sicher?" -- Needs review
L["Right Click Configure"] = "Rechtsklick-Konfiguration"
L["Right clicking the map will open the SexyMap options"] = "Ein Rechtsklick auf die Minimap öffnet die SexyMap Optionen"
L["Rotation Speed (seconds)"] = "Rotationsgeschwindigkeit (Sekunden)"
L["Rounded - Bottom Left"] = "Abgerundet - Unten Links" -- Needs review
L["Rounded - Bottom Right"] = "Abgerundet - Unten Rechts" -- Needs review
L["Rounded - Top Left"] = "Abgerundet - Oben Links" -- Needs review
L["Rounded - Top Right"] = "Abgerundet - Oben Rechts" -- Needs review
L["Route 66"] = "Route 66"
L["Save current settings as preset..."] = "Speichere die aktuellen Einstellungen als Voreinstellung"
L["Scale"] = "Maßstab/Skalierung"
L["Select a preset to load settings from. This will erase any of your current borders."] = "Wähle eine Voreinstellung, um die Einstellungen zu laden. Dies wird alle deine aktuellen Rahmen löschen."
L["Select preset to load"] = "Wähle eine Voreinstellung"
L["SharedMedia Border"] = "SharedMedia Rahmen" -- Needs review
L["SharedMedia Texture"] = "SharedMedia Textur" -- Needs review
L["Show inside chat"] = "Zeige im Chat"
L["Show North Tag"] = "Zeige Norden-Anzeiger" -- Needs review
L["Show on minimap"] = "Zeige an der Minimap"
L["Show %s:"] = "Zeige %s:"
L["Show who pinged"] = "Zeige wer gepingt hat"
L["Snowflake"] = "Schneeflocke"
L["Square"] = "Rechteck"
L["Standard Buttons"] = "Standard-Knöpfe"
L["Static Rotation"] = "Statische Rotation"
L["TexBrowser Not Installed"] = "TexBrowser ist nicht installiert"
L["Text Color"] = "Textfarbe"
L["Texture"] = "Textur"
L["Texture Options"] = "Textur-Optionen"
L["Texture Path"] = "Textur-Pfad"
L["Texture Tint"] = "Textur-Farbton"
L["Text Width"] = "Textbreite" -- Needs review
L["The time it takes (in seconds) to complete one rotation. A setting of 0 turns off rotation."] = "Die Zeit für eine Rotation in Sekunden. Ist der Wert 0, wird die Rotation deaktiviert."
L["This will wipe out any current settings!"] = "Dies wird alle aktuellen Einstellungen löschen."
L["Tile Background"] = "Kachel-Hintergrund" -- Needs review
L["Tile Size"] = "Kachel-Größe" -- Needs review
L["Toggle HudMap On/Off"] = "Schalte HudMap An/Aus" -- Needs review
L["Turn this off if you want another mod to handle which buttons are visible on the minimap."] = "Deaktiviere diese Option, wenn du ein anderes Addon für die Sichtbarkeit der Minimap-Knöpfe benutzt." -- Needs review
L["Use Global Profile"] = "Verwende das globale Profil" -- Needs review
L["User-Submitted Presets"] = "Voreinstellungen von Anwendern" -- Needs review
L["Use the global profile if you want the same look on every character, or use a character-specific profile for a unique look on each character."] = "Verwende das globale Profil, wenn du das gleiche Aussehen für jeden Charakter haben willst, oder benutze ein Charakterspezifisches Profil, um jedem Charakter ein einzigartiges Aussehen zu geben." -- Needs review
L["Vehicle Seat"] = "Fahrzeugsitz"
L["Vertical Position"] = "Vertikale Position"
L["Video Recording Button (Mac OSX Only, When Available)"] = "Videoaufname-Knopf (Nur Mac OSX, falls verfügbar)" -- Needs review
L["Visibility"] = "Sichtbarkeit" -- Needs review
L["Voice Chat Button (When Available)"] = "Voice Chat Knopf (wenn verfügbar)"
L["Width"] = "Breite" -- Needs review
L["You can set a background and edge file for the minimap like you would with any frame. This is useful when you want to create static square backdrops for your minimap."] = "Du kannst einen Hintergrund und Rahmen für die Minimap einstellen, genauso wie bei allen anderen Rahmen. Dies ist nützlich, wenn du einen statischen rechteckigen Hintergrund für die Minimap erstellen möchtest." -- Needs review
L["Zone Text"] = "Zonentext" -- Needs review
L["Zoom In Button"] = "Heranzoom-Knopf"
L["Zoom Out Button"] = "Herauszoom-Knopf"


