
if GetLocale() ~= "itIT" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "1. Sfondo" -- Needs review
L["2. Border"] = "2. Margine" -- Needs review
L["3. Artwork"] = "3. Immagine" -- Needs review
L["4. Overlay"] = "4. Sovrapposizione" -- Needs review
L["5. Highlight"] = "5. Evidenza" -- Needs review
L["Add Blend (additive)"] = "Aggiungi Miscela (aggiuntiva)" -- Needs review
L["Addon Buttons"] = "Pulsanti Addon" -- Needs review
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "Permetti a SexyMap di trascinare i pulsanti intorno alla Minimappa. Disabilita se utilizzi altri mod per posizionare i pulsanti sulla tua Minimappa." -- Needs review
L["Alpha Key (1-bit alpha)"] = "Tasto Trasparenza (1-bit alpha)" -- Needs review
L["Blend Mode"] = "Modo Fusione" -- Needs review
L["Border Color"] = "Colore Margine" -- Needs review
L["Border Edge Size"] = "Dimensione Bordo Margine" -- Needs review
L["Borders"] = "Margini" -- Needs review
L["Border Texture"] = "Trama Magine" -- Needs review
L["Boss Frames"] = "Riquardi Boss" -- Needs review
L["Buttons"] = "Pulsanti" -- Needs review
L["Calendar"] = "Calendario" -- Needs review
L["Challenge Mode Button (When Available)"] = "Bottone Modo Difficoltà (ove disponibile)" -- Needs review
L["Circle"] = "Cerchio" -- Needs review
L["Clamp to screen"] = "Ferma ai margini dello schermo" -- Needs review
L["Clear & start over"] = "Azzera e ricomincia" -- Needs review
L["Clear the current borders and start fresh"] = "Azzera i margini attuali e ricomincia da zero" -- Needs review
L["Clock"] = "Orologio" -- Needs review
L["Coordinates"] = "Coordinate" -- Needs review
L["Create a new border"] = "Crea nuovo margine" -- Needs review
L["Current Borders"] = "Margine Corrente" -- Needs review
L["Delete"] = "Cancella" -- Needs review
L["Diamond"] = "Diamante" -- Needs review
L["Disable (opaque)"] = "Disabilita (opaco)" -- Needs review
L["Disable Rotation"] = "Disabilita Rotazione" -- Needs review
L["Drag Radius"] = "Angolo Trascinamento" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Indicatore Difficoltà Dungeon (ove disponibile)" -- Needs review
L["Dynamic Buttons"] = "Pulsanti Dinamici" -- Needs review
L["Enable"] = "Abilita" -- Needs review
L["Enable a backdrop and border for the minimap. This will let you set square borders more easily."] = "Abilita fondale e margine per la Minimappa. Ti permetterà di sistemare più facilmente i margini quadrati." -- Needs review
L["Enable a HUD minimap. This is very useful for gathering resources, but for technical reasons, the HUD map and the normal minimap can't be shown at the same time. Showing the HUD map will turn off the normal minimap."] = "Abilita una Minimappa HUD. È molto utile per la raccolta delle risorse, ma per ragioni tecniche la mappa HUD e la Minimappa normale non possono essere mostrate contemporaneamente. Far apparire la mappa HUD nasconderà la Minimappa normale." -- Needs review
L["Enable Coordinates"] = "Abilita Coordinate" -- Needs review
L["Enable Hudmap"] = "Abilita Hudmap" -- Needs review
L["Enable Minimap Fader"] = "Abilita Dissolvenza Minimappa" -- Needs review
L["Enable Movers"] = "Abilita Movers" -- Needs review
L["Enter a name to create a new border. The name can be anything you like to help you identify that border."] = "Digita un nome per creare un nuovo margine. Il nome può essere qualunque cosa ti aiuti a identificare il margine." -- Needs review
L["Enter the full path to a texture to use. It's recommended that you use something like |cffff6600TexBrowser|r to find textures to use."] = "Digita il percorso completo a una trama da utilizzare. Si raccomanda di usare qualcosa come |cffff6600TexBrowser|r per trovare la trama da usare." -- Needs review
L["Entry Options"] = "Opzioni della voce" -- Needs review
L["Faded Circle (Large)"] = "Cerchio in dissolvenza (grande)" -- Needs review
L["Faded Circle (Small)"] = "Cerchio in dissolvenza (piccolo)" -- Needs review
L["Faded Square"] = "Quadrato in dissolvenza" -- Needs review
L["Fader"] = "Dissolvenza" -- Needs review
L["Font"] = "Carattere" -- Needs review
L["Font Color"] = "Colore del Carattere" -- Needs review
L["Font Size"] = "Dimensione del Carattere" -- Needs review
L["Force a square texture. Fixed distortion on square textures."] = "Imponi una trama quadrata. Distorsione sistemata con trame quadrate. " -- Needs review
L["Heart"] = "Cuore" -- Needs review
L["Hexagon"] = "Esagono" -- Needs review
L["Hide default border"] = "Nascondi il margine di fabbrica" -- Needs review
L["Hide the default border on the minimap."] = "Nascondi il margine di fabbrica sulla Minimappa." -- Needs review
L["Horizontal Nudge"] = "Colpetto orizzontale" -- Needs review
L["Horizontal Position"] = "Posizione orizzontale" -- Needs review
L["Hover Opacity"] = "Opacità al passaggio del mouse" -- Needs review
L["HUD Color"] = "Colore HUD" -- Needs review


