
if GetLocale() ~= "zhTW" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "1、背景"
L["2. Border"] = "2、邊框"
L["3. Artwork"] = "3、藝術裝飾"
L["4. Overlay"] = "4、覆蓋"
L["5. Highlight"] = "5、高亮"
L["Add Blend (additive)"] = "添加混合（附加式）"
L["Addon Buttons"] = "插件按鈕"
L["A global profile already exists. You will be switched over to it and your UI will be reloaded, are you sure?"] = "一個共用配置檔已存在, 你將會切換至該配置檔並重載插件, 是否確認?" -- Needs review
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "令 SexyMap 能夠拖曳迷你地圖上的按鈕。假如你想用其他插件來拖曳，關閉這個功能"
L["Alpha Key (1-bit alpha)"] = "測試鍵（1位測試）"
L["Always"] = "總是顯示"
L["Are you sure you want to switch back to using a character specific profile? This will reload your UI."] = "你確定要切換回使用角色個別配置檔? 這會重載你的插件." -- Needs review
L["Armored Man"] = "耐久度"
L["A static amount to rotate the texture by."] = "材質靜態旋轉量"
L["Auto Zoom-Out Delay"] = "自動縮小延遲" -- Needs review
L["Background/edge"] = "背景/邊緣"
L["Background Texture"] = "背景材質"
L["Blend Mode"] = "混合模式"
L["Blend (normal)"] = "混合效果（普通）"
L["Border Color"] = "邊框色彩" -- Needs review
L["Border Edge Size"] = "邊框角落尺寸" -- Needs review
L["Borders"] = "邊框"
L["Border Texture"] = "邊框材質" -- Needs review
L["Boss Frames"] = "首領框架" -- Needs review
L["Buttons"] = "按鈕" -- Needs review
L["Calendar"] = "行事曆"
L["Capture Bars"] = "佔領狀態條"
L["Challenge Mode Button (When Available)"] = "挑戰模式按鈕(當可用時)" -- Needs review
L["Circle"] = "圓形"
L["Clamp to screen"] = "不超出螢幕範圍"
L["Clear & start over"] = "重置"
L["Clear the current borders and start fresh"] = "清除當前邊框重新開始設置"
L["Clock"] = "時鐘"
L["Coordinates"] = "坐標"
L["Current Borders"] = "當前邊框"
L["Delete"] = "刪除"
L["Diamond"] = "鑽石形"
L["Disable (opaque)"] = "禁用（不透明）"
L["Disable Rotation"] = "關閉旋轉"
L["Drag Radius"] = "拖曳半徑"
L["Enable"] = "啟用"
L["Enable a backdrop and border for the minimap. This will let you set square borders more easily."] = "啟用迷你地圖的背景與邊框，便於設定方形邊框。"
L["Enable a HUD minimap. This is very useful for gathering resources, but for technical reasons, the HUD map and the normal minimap can't be shown at the same time. Showing the HUD map will turn off the normal minimap."] = "啟用 HUD 式迷你地圖。這個對采集資源很有好處，但是因為技術上的關係，HUD 地圖和原本的迷你地圖不能一起顯示。顯示 HUD 地圖會關閉原本的迷你地圖。"
L["Enable Coordinates"] = "啟用坐標顯示"
L["Enable Hudmap"] = "啟用 HUD 地圖"
L["Enter a name to create a new border. The name can be anything you like to help you identify that border."] = "輸入一個名稱以創建一個新的邊框。可以用任何你想用來幫助你識別此邊框的名稱"
L["Enter the full path to a texture to use. It's recommended that you use something like |cffff6600TexBrowser|r to find textures to use."] = "請輸入要使用的材質完整路徑。建議使用如 TexBrowser 來尋找可用的材質。"
L["Faded Circle (Large)"] = "圓形淡出（大）"
L["Faded Circle (Small)"] = "圓形淡出（小）"
L["Faded Square"] = "方形淡出"
L["Font"] = "字型"
L["Font Color"] = "字形色彩" -- Needs review
L["Font Size"] = "字型大小"
L["Force a square texture. Fixed distortion on square textures."] = "強制使用方形材質，修正因方形材質產生的變形。"
L["Guild Dungeon Difficulty Indicator (When Available)"] = "公會副本難度(當可用時)" -- Needs review
L["Heart"] = "心形"
L["Height"] = "高度" -- Needs review
L["Hexagon"] = "六邊形"
L["Hide default border"] = "隱藏默認邊框"
L["Hide the default border on the minimap."] = "隱藏小地圖默認的邊框"
L["Horizontal Nudge"] = "橫向位移" -- Needs review
L["Horizontal Position"] = "橫向位置" -- Needs review
L["Hover Opacity"] = "滑鼠懸停時不透明度"
L["HUD Color"] = "HUD 顏色"
L["Keybinding"] = "綁定熱鍵"
L["Layer"] = "層級"
L["Let SexyMap control button visibility"] = "SexyMap 管理按鈕可見性"
L["Let SexyMap handle button dragging"] = "SexyMap 接管按鈕拖曳"
L["Lock Button Dragging"] = "鎖定按鈕拖曳"
L["Lock Coordinates"] = "鎖定座標" -- Needs review
L["Lock Minimap"] = "鎖定小地圖" -- Needs review
L["Map Button"] = "世界地圖按鈕"
L["Minimap shape"] = "迷你地圖外觀"
L["Mod Blend (modulative)"] = "模塊混合（模塊式）"
L["Name"] = "名稱"
L["Never"] = "不顯示"
L["No global profile exists. Your current profile will be copied over and used as the global profile, are you sure? This will also reload your UI."] = "無共用配置檔存在, 目前的配置檔將複製至共用配置檔並使用, 是否確認? 這會重載你的插件." -- Needs review
L["Normal Opacity"] = "常規狀態時不透明度"
L["Objectives Tracker"] = "物品追蹤"
L["Octagon"] = "八邊形"
L["Opacity"] = "不透明度"
L["Open TexBrowser"] = "開啟 TexBrowser"
L["Preset"] = "配置檔"
L["Profiles"] = "配置檔"
L["Really delete this border?"] = "確定刪除此邊框？"
L["Really delete this preset? This can't be undone."] = "此動作無法再回復，確定要刪除此設定檔？"
L["Really delete this profile?"] = "確定要刪除這個配置檔?" -- Needs review
L["Reset Current Profile"] = "重置目前配置檔" -- Needs review
L["Resetting this profile will reload your UI, are you sure?"] = "重置配置檔將重載你的插件, 是否確認?" -- Needs review
L["Rotation Speed (seconds)"] = "旋轉速度"
L["Rounded - Bottom Left"] = "方形圓角-左下"
L["Rounded - Bottom Right"] = "方形圓角-右下"
L["Rounded - Top Left"] = "方形圓角-左上"
L["Rounded - Top Right"] = "方形圓角-右上"
L["Route 66"] = "66路形"
L["Save current settings as preset..."] = "儲存目前設定於配置檔"
L["Scale"] = "縮放"
L["Select a preset to load settings from. This will erase any of your current borders."] = "選擇配置檔以載入設定值，這將會清除你目前的邊框設定。"
L["Select preset to load"] = "選擇要載入的配置檔"
L["SharedMedia Border"] = "SharedMedia 邊框"
L["SharedMedia Texture"] = "SharedMedia 材質"
L["Show inside chat"] = "在聊天窗口顯示"
L["Show on minimap"] = "在迷你地圖顯示"
L["Show who pinged"] = "顯示誰點擊地圖"
L["Snowflake"] = "雪花形"
L["Square"] = "方形"
L["Standard Buttons"] = "標準按鈕"
L["Static Rotation"] = "靜態旋轉"
L["TexBrowser Not Installed"] = "尚未安裝 TexBrowser"
L["Text Color"] = "文本顏色"
L["Texture"] = "材質"
L["The time it takes (in seconds) to complete one rotation. A setting of 0 turns off rotation."] = "材質旋轉速度，設定為 0 則停止旋轉"
L["This will wipe out any current settings!"] = "這將會清除你目前的設定值！"
L["Tracking Button"] = "追蹤技能按鈕"
L["Turn this off if you want another mod to handle which buttons are visible on the minimap."] = "假如你用其他插件控制隱藏，關閉這個功能"
L["Use Global Profile"] = "使用共用配置檔" -- Needs review
L["Use the global profile if you want the same look on every character, or use a character-specific profile for a unique look on each character."] = "當你想要所有角色具有相同外觀則使用共用配置檔, 或是使用角色個別配置檔讓不同角色具有不同外觀" -- Needs review
L["Vehicle Seat"] = "載具座位"
L["Width"] = "寬度"
L["You can set a background and edge file for the minimap like you would with any frame. This is useful when you want to create static square backdrops for your minimap."] = "設定你喜歡的迷你地圖設定背景與邊框檔案，便於建立迷你地圖為靜態方形。"


